// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package events

import (
	"database/sql"
)

type ANALYSISDETAIL struct {
	Globalvid int64
	Duration  int64
	Starttime int64
	Stoptime  int64
}

type ANALYSISFILE struct {
	ID        int64
	Filename  string
	Content   string
	Globalpid int64
}

type COMPOSITEEVENT struct {
	ID          int64
	Start       int64
	Cpu         sql.NullInt64
	Threadstate sql.NullInt64
	Globaltid   sql.NullInt64
	Cpucycles   int64
}

type CUBLASEVENT struct {
	Start      int64
	End        int64
	Eventclass int64
	Globaltid  sql.NullInt64
	Nameid     int64
}

type CUDACALLCHAIN struct {
	ID         int64
	Symbol     int64
	Module     int64
	Unresolved sql.NullInt64
	Originalip sql.NullInt64
	Stackdepth int64
}

type CUDAGPUMEMORYPOOLEVENT struct {
	Start                           int64
	Globalpid                       int64
	Deviceid                        int64
	Address                         int64
	Operationtype                   int64
	Pooltype                        int64
	Correlationid                   sql.NullInt64
	Minbytestokeep                  sql.NullInt64
	Localmemorypoolreleasethreshold sql.NullInt64
	Localmemorypoolsize             sql.NullInt64
	Localmemorypoolutilizedsize     sql.NullInt64
}

type CUDAGPUMEMORYUSAGEEVENT struct {
	Start                           int64
	Globalpid                       int64
	Deviceid                        int64
	Contextid                       int64
	Address                         int64
	Pc                              int64
	Bytes                           int64
	Memkind                         int64
	Memoryoperationtype             int64
	Name                            sql.NullString
	Correlationid                   sql.NullInt64
	Localmemorypooladdress          sql.NullInt64
	Localmemorypoolreleasethreshold sql.NullInt64
	Localmemorypoolsize             sql.NullInt64
	Localmemorypoolutilizedsize     sql.NullInt64
	Importedmemorypooladdress       sql.NullInt64
	Importedmemorypoolprocessid     sql.NullInt64
}

type CUDAGRAPHEVENT struct {
	Start           int64
	End             int64
	Eventclass      int64
	Globaltid       sql.NullInt64
	Nameid          int64
	Graphid         sql.NullInt64
	Originalgraphid sql.NullInt64
	Graphexecid     sql.NullInt64
}

type CUDAGRAPHNODEEVENT struct {
	Start               int64
	End                 int64
	Eventclass          int64
	Globaltid           sql.NullInt64
	Nameid              int64
	Graphnodeid         int64
	Originalgraphnodeid sql.NullInt64
}

type CUDAUMCPUPAGEFAULTEVENT struct {
	Start             int64
	Globalpid         int64
	Address           int64
	Originalfaultpc   sql.NullInt64
	Cpuinstruction    int64
	Module            int64
	Unresolvedfaultpc sql.NullInt64
}

type CUDAUMGPUPAGEFAULTEVENT struct {
	Start              int64
	End                int64
	Globalpid          int64
	Deviceid           int64
	Address            int64
	Numberofpagefaults int64
	Faultaccesstype    int64
}

type CUDNNEVENT struct {
	Start      int64
	End        int64
	Eventclass int64
	Globaltid  sql.NullInt64
	Nameid     int64
}

type CUPTIACTIVITYKINDCUDAEVENT struct {
	Deviceid      int64
	Contextid     int64
	Streamid      int64
	Correlationid sql.NullInt64
	Globalpid     sql.NullInt64
	Eventid       int64
}

type CUPTIACTIVITYKINDGRAPHTRACE struct {
	Start          int64
	End            int64
	Deviceid       int64
	Contextid      int64
	Greencontextid sql.NullInt64
	Streamid       int64
	Correlationid  sql.NullInt64
	Globalpid      sql.NullInt64
	Graphid        int64
	Graphexecid    int64
}

type CUPTIACTIVITYKINDKERNEL struct {
	Start                   int64
	End                     int64
	Deviceid                int64
	Contextid               int64
	Streamid                int64
	Correlationid           sql.NullInt64
	Globalpid               sql.NullInt64
	Demangledname           int64
	Shortname               int64
	Mangledname             sql.NullInt64
	Launchtype              sql.NullInt64
	Cacheconfig             sql.NullInt64
	Registersperthread      int64
	Gridx                   int64
	Gridy                   int64
	Gridz                   int64
	Blockx                  int64
	Blocky                  int64
	Blockz                  int64
	Staticsharedmemory      int64
	Dynamicsharedmemory     int64
	Localmemoryperthread    int64
	Localmemorytotal        int64
	Gridid                  int64
	Sharedmemoryexecuted    sql.NullInt64
	Graphnodeid             sql.NullInt64
	Sharedmemorylimitconfig sql.NullInt64
}

type CUPTIACTIVITYKINDMEMCPY struct {
	Start           int64
	End             int64
	Deviceid        int64
	Contextid       int64
	Streamid        int64
	Correlationid   sql.NullInt64
	Globalpid       sql.NullInt64
	Bytes           int64
	Copykind        int64
	Deprecatedsrcid sql.NullInt64
	Srckind         sql.NullInt64
	Dstkind         sql.NullInt64
	Srcdeviceid     sql.NullInt64
	Srccontextid    sql.NullInt64
	Dstdeviceid     sql.NullInt64
	Dstcontextid    sql.NullInt64
	Migrationcause  sql.NullInt64
	Graphnodeid     sql.NullInt64
	Virtualaddress  sql.NullInt64
}

type CUPTIACTIVITYKINDMEMSET struct {
	Start         int64
	End           int64
	Deviceid      int64
	Contextid     int64
	Streamid      int64
	Correlationid sql.NullInt64
	Globalpid     sql.NullInt64
	Value         int64
	Bytes         int64
	Graphnodeid   sql.NullInt64
	Memkind       sql.NullInt64
}

type CUPTIACTIVITYKINDOPENACCDATUM struct {
	Start       int64
	End         int64
	Nameid      int64
	Globaltid   sql.NullInt64
	Eventkind   int64
	Devicetype  int64
	Lineno      int64
	Cudeviceid  int64
	Cucontextid int64
	Custreamid  int64
	Srcfile     sql.NullInt64
	Funcname    sql.NullInt64
	Bytes       sql.NullInt64
	Varname     sql.NullInt64
}

type CUPTIACTIVITYKINDOPENACCLAUNCH struct {
	Start        int64
	End          int64
	Nameid       int64
	Globaltid    sql.NullInt64
	Eventkind    int64
	Devicetype   int64
	Lineno       int64
	Cudeviceid   int64
	Cucontextid  int64
	Custreamid   int64
	Srcfile      sql.NullInt64
	Funcname     sql.NullInt64
	Numgangs     sql.NullInt64
	Numworkers   sql.NullInt64
	Vectorlength sql.NullInt64
	Kernelname   sql.NullInt64
}

type CUPTIACTIVITYKINDOPENACCOTHER struct {
	Start       int64
	End         int64
	Nameid      int64
	Globaltid   sql.NullInt64
	Eventkind   int64
	Devicetype  int64
	Lineno      int64
	Cudeviceid  int64
	Cucontextid int64
	Custreamid  int64
	Srcfile     sql.NullInt64
	Funcname    sql.NullInt64
}

type CUPTIACTIVITYKINDRUNTIME struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Returnvalue   int64
	Callchainid   sql.NullInt64
}

type CUPTIACTIVITYKINDSYNCHRONIZATION struct {
	Start         int64
	End           int64
	Deviceid      int64
	Contextid     int64
	Streamid      int64
	Correlationid sql.NullInt64
	Globalpid     sql.NullInt64
	Synctype      int64
	Eventid       int64
}

type D3D11PIXDEBUGAPI struct {
	Start            int64
	End              int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Shortcontextid   sql.NullInt64
	Frameid          sql.NullInt64
	Color            sql.NullInt64
	Textid           sql.NullInt64
}

type D3D12PIXDEBUGAPI struct {
	Start            int64
	End              int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Shortcontextid   sql.NullInt64
	Frameid          sql.NullInt64
	Color            sql.NullInt64
	Textid           sql.NullInt64
	Commandlisttype  sql.NullInt64
	Objectnameid     sql.NullInt64
	Longcontextid    sql.NullInt64
}

type DIAGNOSTICEVENT struct {
	Timestamp     int64
	Timestamptype int64
	Source        int64
	Severity      int64
	Text          string
	Globalpid     sql.NullInt64
}

type DX12API struct {
	ID               int64
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Shortcontextid   sql.NullInt64
	Frameid          sql.NullInt64
	Color            sql.NullInt64
	Textid           sql.NullInt64
	Commandlisttype  sql.NullInt64
	Objectnameid     sql.NullInt64
	Longcontextid    sql.NullInt64
}

type DX12MEMORYOPERATION struct {
	Gpu             sql.NullInt64
	Rangestart      sql.NullInt64
	Rangeend        sql.NullInt64
	Subresourceid   sql.NullInt64
	Heaptype        sql.NullInt64
	Heapflags       sql.NullInt64
	Cpupageproperty sql.NullInt64
	Nvapiflags      sql.NullInt64
	Traceeventid    int64
}

type DX12WORKLOAD struct {
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Shortcontextid   sql.NullInt64
	Frameid          sql.NullInt64
	Gpu              sql.NullInt64
	Color            sql.NullInt64
	Textid           sql.NullInt64
	Commandlisttype  sql.NullInt64
	Objectnameid     sql.NullInt64
	Longcontextid    sql.NullInt64
}

type ENUMCUDADEVMEMEVENTOPER struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAFUNCCACHECONFIG struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAKERNELLAUNCHTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAMEMCPYOPER struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAMEMKIND struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAMEMPOOLOPER struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAMEMPOOLTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDASHAREDMEMLIMITCONFIG struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAUNIFMEMACCESSTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUDAUNIFMEMMIGRATION struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUPTISTREAMTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMCUPTISYNCTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMD3D12CMDLISTTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMD3D12HEAPFLAG struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMD3D12HEAPTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMD3D12PAGEPROPERTY struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMDIAGNOSTICSEVERITYLEVEL struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMDIAGNOSTICSOURCETYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMDIAGNOSTICTIMESTAMPSOURCE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMDXGIFORMAT struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMETWMEMORYTRANSFERTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMGPUCTXSWITCH struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMNETDEVICEID struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMNETLINKTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMNETVENDORID struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMNSYSEVENTCLASS struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMNSYSEVENTTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMNVDRIVEREVENTID struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENACCDEVICE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENACCEVENTKIND struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENGLDEBUGSEVERITY struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENGLDEBUGSOURCE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENGLDEBUGTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPDISPATCH struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPEVENTKIND struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPMUTEX struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPSYNCREGION struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPTASKFLAG struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPTASKSTATUS struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPTHREAD struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMOPENMPWORK struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMPMUEVENTSOURCE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMPMUUNITTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMSAMPLINGTHREADSTATE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMSLITRANSER struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMSTACKUNWINDMETHOD struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMVIDEOENGINECODEC struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMVIDEOENGINETYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMVULKANPIPELINECREATIONFLAG struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMWDDMENGINETYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMWDDMINTERRUPTTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMWDDMPACKETTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMWDDMPAGINGQUEUETYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ENUMWDDMVIDMMOPTYPE struct {
	ID    int64
	Name  sql.NullString
	Label sql.NullString
}

type ETWEVENT struct {
	Timestamp  int64
	Processid  sql.NullInt64
	Threadid   sql.NullInt64
	Providerid int64
	Taskid     int64
	Eventid    int64
	Version    int64
	Opcode     sql.NullInt64
	Data       string
}

type ETWPROVIDER struct {
	Providerid     int64
	Providernameid int64
	Guid           string
}

type ETWTASK struct {
	Tasknameid int64
	Taskid     int64
	Providerid int64
}

type GENERICEVENT struct {
	Rawtimestamp int64
	Timestamp    sql.NullInt64
	Typeid       int64
	Data         string
}

type GENERICEVENTSOURCE struct {
	Sourceid int64
	Data     string
}

type GENERICEVENTTYPE struct {
	Typeid   int64
	Sourceid int64
	Data     string
}

type GPUCONTEXTSWITCHEVENT struct {
	Tag       int64
	Vmid      int64
	Seqno     int64
	Contextid int64
	Timestamp int64
	Globalpid sql.NullInt64
	Gpuid     sql.NullInt64
}

type GPUMETRIC struct {
	Timestamp sql.NullInt64
	Typeid    int64
	Metricid  int64
	Value     int64
}

type KHRDEBUGEVENT struct {
	Eventclass    int64
	Start         int64
	End           sql.NullInt64
	Textid        sql.NullInt64
	Globaltid     sql.NullInt64
	Source        sql.NullInt64
	Khrdtype      sql.NullInt64
	ID            sql.NullInt64
	Severity      sql.NullInt64
	Correlationid sql.NullInt64
	Context       sql.NullInt64
}

type MEMORYTRANSFEREVENT struct {
	Start                  int64
	Globaltid              sql.NullInt64
	Gpu                    sql.NullInt64
	Taskid                 int64
	Eventid                int64
	Allocationglobalhandle int64
	Dmabuffer              int64
	Size                   int64
	Offset                 int64
	Memorytransfertype     int64
}

type METADATACAPTURE struct {
	Name  string
	Value sql.NullString
}

type METADATAEXPORT struct {
	Name  string
	Value sql.NullString
}

type MPICOLLECTIVESEVENT struct {
	Start         int64
	End           sql.NullInt64
	Globaltid     sql.NullInt64
	Textid        sql.NullInt64
	Commhandle    sql.NullInt64
	Rootrank      sql.NullInt64
	Size          sql.NullInt64
	Recvsize      sql.NullInt64
	Requesthandle sql.NullInt64
}

type MPICOMMUNICATOR struct {
	Rank         sql.NullInt64
	Timestamp    sql.NullInt64
	Commhandle   sql.NullInt64
	Parenthandle sql.NullInt64
	Localrank    sql.NullInt64
	Size         sql.NullInt64
	Grouproot    sql.NullInt64
	Grouprootuid sql.NullInt64
	Members      sql.NullString
}

type MPIOTHEREVENT struct {
	Start     int64
	End       sql.NullInt64
	Globaltid sql.NullInt64
	Textid    sql.NullInt64
}

type MPIP2PEVENT struct {
	Start         int64
	End           sql.NullInt64
	Globaltid     sql.NullInt64
	Textid        sql.NullInt64
	Commhandle    sql.NullInt64
	Tag           sql.NullInt64
	Remoterank    sql.NullInt64
	Size          sql.NullInt64
	Requesthandle sql.NullInt64
}

type MPIRANK struct {
	Globaltid int64
	Rank      int64
}

type MPISTARTWAITEVENT struct {
	Start         int64
	End           sql.NullInt64
	Globaltid     sql.NullInt64
	Textid        sql.NullInt64
	Requesthandle sql.NullInt64
}

type NETIBSWITCHMETRIC struct {
	Start         int64
	End           int64
	Globalid      int64
	Metricslistid int64
	Metricsidx    int64
	Value         int64
}

type NETNICMETRIC struct {
	Start         int64
	End           int64
	Globalid      int64
	Metricslistid int64
	Metricsidx    int64
	Value         int64
}

type NICIDMAP struct {
	Nicid    int64
	Globalid int64
}

type NVLOADBALANCEEVENT struct {
	Start                    int64
	End                      int64
	Globaltid                int64
	Gpu                      int64
	Eventid                  int64
	Task                     string
	Averagefps               float64
	Queuedframes             float64
	Averagequeuedframes      float64
	Currentcputime           float64
	Averagecputime           float64
	Averagestalltime         float64
	Averagecpuidletime       float64
	Isgpualmostoneframeahead int64
}

type NVLOADBALANCEMASTEREVENT struct {
	Start                    int64
	End                      int64
	Globaltid                int64
	Gpu                      int64
	Eventid                  int64
	Task                     string
	Framecount               int64
	Frametime                float64
	Averageframetime         float64
	Averagelatency           float64
	Minlatency               float64
	Averagequeuedframes      float64
	Totalactivems            float64
	Totalidlems              float64
	Idlepercent              float64
	Isgpualmostoneframeahead int64
}

type NVTXEVENT struct {
	Start        int64
	End          sql.NullInt64
	Eventtype    int64
	Rangeid      sql.NullInt64
	Category     sql.NullInt64
	Color        sql.NullInt64
	Text         sql.NullString
	Globaltid    sql.NullInt64
	Endglobaltid sql.NullInt64
	Textid       sql.NullInt64
	Domainid     sql.NullInt64
	Uint64value  sql.NullInt64
	Int64value   sql.NullInt64
	Doublevalue  sql.NullFloat64
	Uint32value  sql.NullInt64
	Int32value   sql.NullInt64
	Floatvalue   sql.NullFloat64
	Jsontextid   sql.NullInt64
	Jsontext     sql.NullString
}

type NVVIDEODECODERAPI struct {
	Start      int64
	End        int64
	Eventclass int64
	Globaltid  sql.NullInt64
	Nameid     int64
}

type NVVIDEOENCODERAPI struct {
	Start      int64
	End        int64
	Eventclass int64
	Globaltid  sql.NullInt64
	Nameid     int64
}

type NVVIDEOJPEGAPI struct {
	Start      int64
	End        int64
	Eventclass int64
	Globaltid  sql.NullInt64
	Nameid     int64
}

type OPENGLAPI struct {
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Endglobaltid     sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Endnameid        sql.NullInt64
	Returnvalue      int64
	Frameid          sql.NullInt64
	Contextid        sql.NullInt64
	Gpu              sql.NullInt64
	Display          sql.NullInt64
}

type OPENGLWORKLOAD struct {
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Endglobaltid     sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Endnameid        sql.NullInt64
	Returnvalue      int64
	Frameid          sql.NullInt64
	Contextid        sql.NullInt64
	Gpu              sql.NullInt64
	Display          sql.NullInt64
}

type OPENMPEVENTKINDCANCEL struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Taskid        sql.NullInt64
}

type OPENMPEVENTKINDCRITICALSECTION struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Waitid        sql.NullInt64
}

type OPENMPEVENTKINDDISPATCH struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
}

type OPENMPEVENTKINDFLUSH struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Threadid      sql.NullInt64
}

type OPENMPEVENTKINDLOCKDESTROY struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Waitid        sql.NullInt64
}

type OPENMPEVENTKINDLOCKINIT struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Waitid        sql.NullInt64
}

type OPENMPEVENTKINDMASTER struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
}

type OPENMPEVENTKINDMUTEXRELEASED struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Waitid        sql.NullInt64
	Taskid        sql.NullInt64
}

type OPENMPEVENTKINDMUTEXWAIT struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Waitid        sql.NullInt64
	Taskid        sql.NullInt64
}

type OPENMPEVENTKINDPARALLEL struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parallelid    sql.NullInt64
	Parenttaskid  sql.NullInt64
}

type OPENMPEVENTKINDREDUCTION struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
}

type OPENMPEVENTKINDSYNCREGION struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
	Kind          sql.NullInt64
}

type OPENMPEVENTKINDSYNCREGIONWAIT struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
	Kind          sql.NullInt64
}

type OPENMPEVENTKINDTASK struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
	Kind          sql.NullInt64
}

type OPENMPEVENTKINDTASKCREATE struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Parenttaskid  sql.NullInt64
	Newtaskid     sql.NullInt64
}

type OPENMPEVENTKINDTASKSCHEDULE struct {
	Start           int64
	End             int64
	Eventclass      int64
	Globaltid       sql.NullInt64
	Correlationid   sql.NullInt64
	Nameid          int64
	Eventkind       sql.NullInt64
	Parallelid      sql.NullInt64
	Priortaskid     sql.NullInt64
	Priortaskstatus sql.NullInt64
	Nexttaskid      sql.NullInt64
}

type OPENMPEVENTKINDTHREAD struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Threadid      sql.NullInt64
	Threadtype    sql.NullInt64
}

type OPENMPEVENTKINDWORKSHARE struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Correlationid sql.NullInt64
	Nameid        int64
	Eventkind     sql.NullInt64
	Kind          sql.NullInt64
	Parallelid    sql.NullInt64
	Taskid        sql.NullInt64
	Count         sql.NullInt64
}

type OSRTAPI struct {
	Start        int64
	End          int64
	Eventclass   int64
	Globaltid    sql.NullInt64
	Nameid       int64
	Returnvalue  int64
	Nestinglevel sql.NullInt64
	Callchainid  int64
}

type OSRTCALLCHAIN struct {
	ID           int64
	Symbol       int64
	Module       int64
	Kernelmode   sql.NullInt64
	Thumbcode    sql.NullInt64
	Unresolved   sql.NullInt64
	Specialentry sql.NullInt64
	Originalip   sql.NullInt64
	Unwindmethod sql.NullInt64
	Stackdepth   int64
}

type PERFEVENTCPUMETRICEVENT struct {
	Start       int64
	End         int64
	Vmid        sql.NullInt64
	Componentid sql.NullInt64
	Metricid    sql.NullInt64
	Value       sql.NullFloat64
}

type PERFEVENTCPURAWEVENT struct {
	Start       int64
	End         int64
	Vmid        sql.NullInt64
	Componentid sql.NullInt64
	Eventid     sql.NullInt64
	Count       sql.NullInt64
}

type PMUEVENT struct {
	Start     int64
	End       int64
	Globalvm  int64
	Cpu       int64
	CounterID sql.NullInt64
}

type PMUEVENTCOUNTER struct {
	ID    int64
	Idx   int64
	Value int64
}

type PMUEVENTREQUEST struct {
	ID        int64
	Eventid   sql.NullInt64
	Source    int64
	UnitType  int64
	EventName sql.NullString
}

type PROCESS struct {
	Globalpid sql.NullInt64
	Pid       sql.NullInt64
	Name      sql.NullString
}

type PROFILEROVERHEAD struct {
	Start       int64
	End         int64
	Globaltid   sql.NullInt64
	Nameid      int64
	Returnvalue int64
}

type ProcessStream struct {
	Globalpid  int64
	Filenameid int64
	Contentid  int64
}

type SAMPLINGCALLCHAIN struct {
	ID           int64
	Symbol       int64
	Module       int64
	Kernelmode   sql.NullInt64
	Thumbcode    sql.NullInt64
	Unresolved   sql.NullInt64
	Specialentry sql.NullInt64
	Originalip   sql.NullInt64
	Unwindmethod sql.NullInt64
	Stackdepth   int64
}

type SCHEDEVENT struct {
	Start     int64
	Cpu       int64
	Isschedin int64
	Globaltid sql.NullInt64
}

type SLIP2P struct {
	Start                     int64
	End                       int64
	Eventclass                int64
	Globaltid                 sql.NullInt64
	Gpu                       int64
	Frameid                   int64
	Transferskipped           int64
	Srcgpu                    int64
	Dstgpu                    int64
	Numsubresources           int64
	Resourcesize              int64
	Subresourceidx            int64
	Smplwidth                 sql.NullInt64
	Smplheight                sql.NullInt64
	Smpldepth                 sql.NullInt64
	Bytesperelement           sql.NullInt64
	Dxgiformat                sql.NullInt64
	Logsurfacenames           sql.NullString
	Transferinfo              sql.NullInt64
	Isearlypushmanagedbynvapi sql.NullInt64
	Useasyncp2pforresolve     sql.NullInt64
	Transferfuncname          sql.NullString
	Regimename                sql.NullString
	Debugname                 sql.NullString
	Bindtype                  sql.NullString
}

type SLIQUERY struct {
	Start                   int64
	End                     int64
	Eventclass              int64
	Globaltid               sql.NullInt64
	Gpu                     int64
	Frameid                 int64
	Occqueryissued          int64
	Occqueryasked           int64
	Eventqueryissued        int64
	Eventqueryasked         int64
	Numberoftransferevents  int64
	Amountoftransferreddata int64
}

type SLISTAT struct {
	Start              int64
	End                int64
	Eventclass         int64
	Globaltid          sql.NullInt64
	Gpu                int64
	Countcomplexframes int64
	Countstats         int64
	Totalinactivetime  int64
	Minpbsize          int64
	Maxpbsize          int64
	Totalpbsize        int64
}

type StringId struct {
	ID    int64
	Value string
}

type TARGETINFOCOMPONENT struct {
	Componentid       int64
	Name              string
	Instance          int64
	Parentcomponentid int64
}

type TARGETINFOCUDACONTEXTINFO struct {
	Nullstreamid    int64
	Hwid            int64
	Vmid            int64
	Processid       int64
	Deviceid        int64
	Contextid       int64
	Parentcontextid sql.NullInt64
	Isgreencontext  sql.NullInt64
}

type TARGETINFOCUDASTREAM struct {
	Streamid  int64
	Hwid      int64
	Vmid      int64
	Processid int64
	Contextid int64
	Priority  int64
	Flag      int64
}

type TARGETINFOGPU struct {
	Vmid                  int64
	ID                    int64
	Name                  sql.NullString
	Buslocation           sql.NullString
	Isdiscrete            sql.NullInt64
	L2cachesize           sql.NullInt64
	Totalmemory           sql.NullInt64
	Memorybandwidth       sql.NullInt64
	Clockrate             sql.NullInt64
	Smcount               sql.NullInt64
	Pwgpuid               sql.NullInt64
	Uuid                  sql.NullString
	Luid                  sql.NullInt64
	Chipname              sql.NullString
	Cudevice              sql.NullInt64
	Ctxswdevpath          sql.NullString
	Ctrldevpath           sql.NullString
	Revision              sql.NullInt64
	Nodemask              sql.NullInt64
	Constantmemory        sql.NullInt64
	Maxipc                sql.NullInt64
	Maxregistersperblock  sql.NullInt64
	Maxshmemperblock      sql.NullInt64
	Maxshmemperblockoptin sql.NullInt64
	Maxshmempersm         sql.NullInt64
	Maxregisterspersm     sql.NullInt64
	Threadsperwarp        sql.NullInt64
	Asyncengines          sql.NullInt64
	Maxwarpspersm         sql.NullInt64
	Maxblockspersm        sql.NullInt64
	Maxthreadsperblock    sql.NullInt64
	Maxblockdimx          sql.NullInt64
	Maxblockdimy          sql.NullInt64
	Maxblockdimz          sql.NullInt64
	Maxgriddimx           sql.NullInt64
	Maxgriddimy           sql.NullInt64
	Maxgriddimz           sql.NullInt64
	Computemajor          sql.NullInt64
	Computeminor          sql.NullInt64
	Smmajor               sql.NullInt64
	Smminor               sql.NullInt64
}

type TARGETINFOGPUMETRIC struct {
	Typeid     int64
	Sourceid   int64
	Typename   string
	Metricid   int64
	Metricname string
}

type TARGETINFONETWORKMETRIC struct {
	Metricslistid int64
	Metricsidx    int64
	Name          string
	Description   string
	Unit          string
}

type TARGETINFONICINFO struct {
	Globalid  sql.NullInt64
	Statename string
	Nicid     int64
	Name      string
	Deviceid  int64
	Vendorid  int64
	Linklayer int64
}

type TARGETINFONVTXCUDACONTEXT struct {
	Name      string
	Hwid      int64
	Vmid      int64
	Processid int64
	Deviceid  int64
	Contextid int64
}

type TARGETINFONVTXCUDADEVICE struct {
	Name     string
	Hwid     int64
	Vmid     int64
	Deviceid int64
}

type TARGETINFONVTXCUDASTREAM struct {
	Name      string
	Hwid      int64
	Vmid      int64
	Processid int64
	Deviceid  int64
	Contextid int64
	Streamid  int64
}

type TARGETINFOPERFMETRIC struct {
	ID          int64
	Name        string
	Description string
	Unit        string
}

type TARGETINFOPROCESS struct {
	Processid     int64
	Openglversion string
	Correlationid int64
	Nameid        int64
}

type TARGETINFOSESSIONSTARTTIME struct {
	Utcepochns sql.NullInt64
	Utctime    sql.NullString
	Localtime  sql.NullString
}

type TARGETINFOSYSTEMENV struct {
	Globalvid    sql.NullInt64
	Devstatename string
	Name         string
	Nameenum     int64
	Value        string
}

type TARGETINFOWDDMCONTEXT struct {
	Context      int64
	Enginetype   int64
	Nodeordinal  int64
	Friendlyname string
}

type TARGETINFOXMCSPEC struct {
	Vmid     int64
	Clientid int64
	Type     string
	Name     string
	Groupid  string
}

type TRACEPROCESSEVENTNVMEDIUM struct {
	Start         int64
	End           int64
	Eventclass    int64
	Globaltid     sql.NullInt64
	Nameid        int64
	Correlationid sql.NullInt64
}

type ThreadName struct {
	Nameid    int64
	Priority  sql.NullInt64
	Globaltid sql.NullInt64
}

type UCPEVENT struct {
	Start     int64
	End       sql.NullInt64
	Globaltid sql.NullInt64
	Textid    sql.NullInt64
}

type UCPPROGRESSEVENT struct {
	Start         int64
	End           sql.NullInt64
	Globaltid     sql.NullInt64
	Textid        sql.NullInt64
	Bufferaddr    sql.NullInt64
	Packedsize    sql.NullInt64
	Peerworkeruid sql.NullInt64
	Tag           sql.NullInt64
}

type UCPSUBMITEVENT struct {
	Start         int64
	End           sql.NullInt64
	Globaltid     sql.NullInt64
	Textid        sql.NullInt64
	Bufferaddr    sql.NullInt64
	Packedsize    sql.NullInt64
	Peerworkeruid sql.NullInt64
	Tag           sql.NullInt64
}

type UCPWORKER struct {
	Globaltid int64
	Workeruid int64
}

type UNCOREPMUEVENT struct {
	Start     int64
	End       int64
	Globalvm  int64
	Clusterid sql.NullInt64
	Counterid sql.NullInt64
}

type UNCOREPMUEVENTVALUE struct {
	ID        int64
	Type      int64
	Value     int64
	Rawid     int64
	Clusterid sql.NullInt64
}

type VULKANAPI struct {
	ID               int64
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Contextid        sql.NullInt64
}

type VULKANDEBUGAPI struct {
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Contextid        sql.NullInt64
	Color            sql.NullInt64
	Textid           sql.NullInt64
}

type VULKANPIPELINECREATIONEVENT struct {
	ID           int64
	Duration     sql.NullInt64
	Flags        sql.NullInt64
	Traceeventid int64
}

type VULKANPIPELINESTAGEEVENT struct {
	ID              int64
	Duration        sql.NullInt64
	Flags           sql.NullInt64
	Creationeventid int64
}

type VULKANWORKLOAD struct {
	Start            int64
	End              int64
	Eventclass       int64
	Globaltid        sql.NullInt64
	Correlationid    sql.NullInt64
	Endcorrelationid sql.NullInt64
	Nameid           int64
	Gpu              sql.NullInt64
	Contextid        sql.NullInt64
	Color            sql.NullInt64
	Textid           sql.NullInt64
}

type WDDMDMAPACKETINFOEVENT struct {
	Start                 int64
	End                   int64
	Globaltid             sql.NullInt64
	Gpu                   int64
	Context               int64
	Ulicompletionid       int64
	Faultedvirtualaddress int64
	Faultedprocesshandle  int64
	Packettype            int64
	Ulqueuesubmitsequence int64
	Interrupttype         int64
	Quantumstatus         int64
	Pagefaultflags        int64
	Enginetype            int64
}

type WDDMDMAPACKETSTARTEVENT struct {
	Start                 int64
	End                   int64
	Globaltid             sql.NullInt64
	Gpu                   int64
	Context               int64
	Queuepacketcontext    int64
	Ulisubmissionid       int64
	Dmabuffer             int64
	Packettype            int64
	Ulqueuesubmitsequence int64
	Quantumstatus         int64
	Enginetype            int64
}

type WDDMDMAPACKETSTOPEVENT struct {
	Start                 int64
	End                   int64
	Globaltid             sql.NullInt64
	Gpu                   int64
	Context               int64
	Ulicompletionid       int64
	Packettype            int64
	Ulqueuesubmitsequence int64
	Preempted             int64
	Enginetype            int64
}

type WDDMEVICTALLOCATIONEVENT struct {
	Start            int64
	End              int64
	Globaltid        sql.NullInt64
	Gpu              int64
	Allocationhandle int64
}

type WDDMHWQUEUEEVENT struct {
	Start            int64
	End              int64
	Globaltid        sql.NullInt64
	Gpu              int64
	Context          int64
	Hwqueue          int64
	Parentdxghwqueue int64
}

type WDDMPAGINGQUEUEPACKETINFOEVENT struct {
	Start             int64
	End               int64
	Globaltid         sql.NullInt64
	Gpu               int64
	Pagingqueue       int64
	Pagingqueuepacket int64
	Sequenceid        int64
}

type WDDMPAGINGQUEUEPACKETSTARTEVENT struct {
	Start             int64
	End               int64
	Globaltid         sql.NullInt64
	Gpu               int64
	Dxgdevice         sql.NullInt64
	Dxgadapter        sql.NullInt64
	Pagingqueue       int64
	Pagingqueuepacket int64
	Sequenceid        int64
	Alloc             sql.NullInt64
	Vidmmoptype       int64
	Pagingqueuetype   int64
}

type WDDMPAGINGQUEUEPACKETSTOPEVENT struct {
	Start             int64
	End               int64
	Globaltid         sql.NullInt64
	Gpu               int64
	Pagingqueue       int64
	Pagingqueuepacket int64
	Sequenceid        int64
}

type WDDMQUEUEPACKETINFOEVENT struct {
	Start          int64
	End            int64
	Globaltid      sql.NullInt64
	Gpu            int64
	Context        int64
	Packettype     int64
	Submitsequence int64
	Enginetype     int64
}

type WDDMQUEUEPACKETSTARTEVENT struct {
	Start                 int64
	End                   int64
	Globaltid             sql.NullInt64
	Gpu                   int64
	Context               int64
	Dmabuffersize         int64
	Dmabuffer             int64
	Queuepacket           int64
	Progressfencevalue    int64
	Packettype            int64
	Submitsequence        int64
	Allocationlistsize    int64
	Patchlocationlistsize int64
	Present               int64
	Enginetype            int64
	Syncobject            sql.NullInt64
}

type WDDMQUEUEPACKETSTOPEVENT struct {
	Start          int64
	End            int64
	Globaltid      sql.NullInt64
	Gpu            int64
	Context        int64
	Queuepacket    int64
	Packettype     int64
	Submitsequence int64
	Preempted      int64
	Timeouted      int64
	Enginetype     int64
}
